<template>
    <div class="account-statement-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header (matches Account Balance template structure) -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Outlet: {{ reportHeaderData.outletName }}
                            </div>
                            <div v-if="reportHeaderData.phone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.phone }}
                            </div>
                            <div v-if="reportHeaderData.address" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.address }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Date Range: {{ reportHeaderData.dateRange }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Payment Account: {{ reportHeaderData.paymentAccountName }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Account Statement Table -->
                <VDataTable
                    :items="tableItems"
                    :headers="exportHeaders"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                    :items-per-page="-1"
                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                {{ !selectedPaymentMethodName || selectedPaymentMethodName === 'All Payment Account' 
                                    ? 'Please select a payment account to view statement' 
                                    : 'No statement records found with current filters' }}
                            </div>
                        </div>
                    </template>

                    <!-- SN -->
                    <template #item.sn="{ item }">
                        <span class="font-weight-medium" :class="item.is_opening_row ? 'font-weight-bold' : ''">
                            {{ item.sn }}
                        </span>
                    </template>

                    <!-- Date -->
                    <template #item.date="{ item }">
                        <span class="font-weight-medium" :class="item.is_opening_row ? 'font-weight-bold' : ''">
                            {{ item.is_opening_row ? '-' : formatDate(item.date) }}
                        </span>
                    </template>

                    <!-- Title with multiline support -->
                    <template #item.title="{ item }">
                        <div 
                            class="text-high-emphasis" 
                            :class="item.is_opening_row ? 'font-weight-bold' : ''"
                            style="white-space: pre-line; line-height: 1.5;"
                        >
                            {{ item.title }}
                        </div>
                    </template>

                    <!-- Debit formatting -->
                    <template #item.debit="{ item }">
                        <span 
                            v-if="item.debit > 0"
                            class="font-weight-bold"
                        >
                            {{ formatAmount(item.debit) }}
                        </span>
                        <span v-else class="text-medium-emphasis">-</span>
                    </template>

                    <!-- Credit formatting -->
                    <template #item.credit="{ item }">
                        <span 
                            v-if="item.credit > 0"
                            class="font-weight-bold"
                        >
                            {{ formatAmount(item.credit) }}
                        </span>
                        <span v-else class="text-medium-emphasis">-</span>
                    </template>

                    <!-- Balance formatting -->
                    <template #item.balance="{ item }">
                        <span 
                            class="font-weight-bold">
                            {{ formatAmount(item.balance) }}
                        </span>
                    </template>

                    <!-- Added By -->
                    <template #item.added_by="{ item }">
                        <p 
                            v-if="!item.is_opening_row"
           
                        >
                            {{ item.added_by || 'N/A' }}
                        </p>
                        <span v-else class="text-medium-emphasis">-</span>
                    </template>

                    <!-- Added Date Time -->
                    <template #item.added_date_time="{ item }">
                        <span class="text-medium-emphasis">
                            {{ item.is_opening_row ? '-' : formatDateWithTime(item.added_date_time) }}
                        </span>
                    </template>

                    <!-- Summary Row as Data Table Footer (matches Account Balance) -->
                    <template #body.append>
                        <tr>
                            
                            <td class="text-h6 font-weight-bold">
                            </td>
                            <td class="text-h6 font-weight-bold">
                            </td>
                            <td class="text-h6 font-weight-bold">
                            </td>
                            <td class="text-h6 font-weight-bold">
                                Total Debit:
                                {{ formatAmount(totalDebit) }}
                            </td>
  
                            <td class="text-h6 font-weight-bold">
                                Total Credit:
                                {{ formatAmount(totalCredit) }}
                            </td>
                            <td class="text-h6 font-weight-bold">
                                Closing Balance:
                                {{ formatAmount(closingBalance) }}
                            </td>
                            <td class="text-h6 font-weight-bold">
                            </td>
                            <td class="text-h6 font-weight-bold">
                            </td>
                        </tr>
                    </template>
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'

const { formatDate, formatAmount, formatDateWithTime } = useCompanyFormatters()
const { userData } = useUserData()

const props = defineProps({
    statements: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    selectedPaymentMethodName: {
        type: String,
        default: 'All Payment Account'
    },
    isLoading: {
        type: Boolean,
        default: false
    },
    exportHeaders: {
        type: Array,
        default: () => []
    },
    summaryData: {
        type: Object,
        default: () => ({})
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:headerData'])

// Helper functions
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

const calculateTotal = (field) => {
    return props.statements.reduce((sum, item) => {
        return sum + (parseFloat(item[field]) || 0)
    }, 0)
}

// Computed property for total debit and credit
const totalDebit = computed(() => calculateTotal('debit'))
const totalCredit = computed(() => calculateTotal('credit'))

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Get opening and closing balances from summary or calculate
const openingBalance = computed(() => {
    return props.summaryData?.openingBalance || 0
})

const closingBalance = computed(() => {
    return props.summaryData?.closingBalance || (props.statements.length > 0 ? props.statements[props.statements.length - 1]?.balance : 0) || 0
})

// Table items with opening balance row
const tableItems = computed(() => {
    // If no payment method selected or no opening balance, return regular statements
    if (!props.selectedPaymentMethodName || props.selectedPaymentMethodName === 'All Payment Account') {
        return props.statements
    }

    // Create opening balance row
    const openingRow = {
        sn: '',
        date: '',
        title: 'Opening Balance',
        debit: 0,
        credit: 0,
        balance: openingBalance.value,
        added_by: '',
        added_date_time: '',
        is_opening_row: true
    }

    // Return opening balance row followed by regular statements
    return [openingRow, ...props.statements]
})

// Report header data for exports (matches Account Balance structure)
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Account Statement Report',
        outletName: props.selectedBranchName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value,
        paymentAccountName: props.selectedPaymentMethodName
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || 'N/A'
        headerData.address = props.selectedBranch.address || 'N/A'
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:headerData', newVal)
}, { immediate: true })
</script>

<style lang="scss" scoped>
.account-statement-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
.summary-row {
    background-color: rgba(var(--v-theme-primary), 0.05);
    border-top: 2px solid rgb(var(--v-theme-primary));
    
    td {
        padding: 16px 12px;
        border-top: 2px solid rgb(var(--v-theme-primary));
    }
}
</style>

