<template>
    <div class="balance-sheet-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Outlet: {{ reportHeaderData.outletName }}
                            </div>
                            <div v-if="reportHeaderData.phone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.phone }}
                            </div>
                            <div v-if="reportHeaderData.address" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.address }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Assets Section -->
                <div class="mb-6">
                    <h5 class="text-h5 mb-4 text-success">Assets</h5>
                    <VDataTable
                        :items="assets"
                        :headers="assetsHeaders"
                        class="text-no-wrap mb-4"
                        :loading="isLoading"
                        hide-default-footer
                        :items-per-page="-1"
                    >
                        <!-- Loading state -->
                        <template #loading>
                            <VSkeletonLoader type="table-row" :rows="5" />
                        </template>

                        <!-- No data state -->
                        <template #no-data>
                            <div class="d-flex align-center justify-center pa-4">
                                <VIcon icon="tabler-alert-circle" class="me-2" />
                                <div>No asset records found</div>
                            </div>
                        </template>

                        <!-- SN -->
                        <template #item.sn="{ item }">
                            <span class="font-weight-medium">{{ item.sn }}</span>
                        </template>

                        <!-- Title -->
                        <template #item.title="{ item }">
                            <span class="text-high-emphasis font-weight-medium">
                                {{ item.title }}
                            </span>
                        </template>

                        <!-- Amount -->
                        <template #item.amount="{ item }">
                            <span class="font-weight-bold">
                                {{ formatAmount(item.amount) }}
                            </span>
                        </template>

                        <template #body.append>
                            <tr>
                                <td class="text-h6 font-weight-bold">
                                </td>
                                <td class="text-h6 font-weight-bold">
                                    <span class="d-flex align-center">
                                        Total Assets
                                    </span>
                                </td>
                                <td class="text-h6 font-weight-bold">
                                    {{ formatAmount(calculateTotal(assets, 'amount')) }}
                                </td>
                            </tr>
                        </template>
                    </VDataTable>
                </div>

                <!-- Liabilities Section -->
                <div class="mb-6">
                    <h5 class="text-h5 mb-4 text-error">Liabilities</h5>
                    <VDataTable
                        :items="liabilities"
                        :headers="liabilitiesHeaders"
                        class="text-no-wrap mb-4"
                        :loading="isLoading"
                        hide-default-footer
                        :items-per-page="-1"
                    >
                        <!-- Loading state -->
                        <template #loading>
                            <VSkeletonLoader type="table-row" :rows="5" />
                        </template>

                        <!-- No data state -->
                        <template #no-data>
                            <div class="d-flex align-center justify-center pa-4">
                                <VIcon icon="tabler-alert-circle" class="me-2" />
                                <div>No liability records found</div>
                            </div>
                        </template>

                        <!-- SN -->
                        <template #item.sn="{ item }">
                            <span class="font-weight-medium">{{ item.sn }}</span>
                        </template>

                        <!-- Title -->
                        <template #item.title="{ item }">
                            <span class="text-high-emphasis font-weight-medium">
                                {{ item.title }}
                            </span>
                        </template>

                        <!-- Amount -->
                        <template #item.amount="{ item }">
                            <span class="font-weight-bold">
                                {{ formatAmount(item.amount) }}
                            </span>
                        </template>

                        <template #body.append>
                            <tr>
                                <td class="text-h6 font-weight-bold">
                                </td>
                                <td class="text-h6 font-weight-bold">
                                    <span class="d-flex align-center">
                                        Total Liabilities
                                    </span>
                                </td>
                                <td class="text-h6 font-weight-bold">
                                    {{ formatAmount(calculateTotal(liabilities, 'amount')) }}
                                </td>
                            </tr>
                        </template>
                    </VDataTable>
                </div>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'
import { useCompanySettings } from '@/composables/useCompanySettings'

const { formatDate, formatAmount, formatDateWithTime } = useCompanyFormatters()
const { userData } = useUserData()
const { companySettings } = useCompanySettings()

const props = defineProps({
    assets: {
        type: Array,
        default: () => []
    },
    liabilities: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    isLoading: {
        type: Boolean,
        default: false
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:headerData'])

const assetsHeaders = [
    { title: 'SN', key: 'sn', sortable: false },
    { title: 'Assets', key: 'title', sortable: false },
    { title: 'Amount', key: 'amount', sortable: false }
]

const liabilitiesHeaders = [
    { title: 'SN', key: 'sn', sortable: false },
    { title: 'Liability', key: 'title', sortable: false },
    { title: 'Amount', key: 'amount', sortable: false }
]

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Helper functions
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

const calculateTotal = (items, field) => {
    return items.reduce((sum, item) => {
        return sum + (parseFloat(item[field]) || 0)
    }, 0)
}

const netWorth = computed(() => {
    const totalAssets = calculateTotal(props.assets, 'amount')
    const totalLiabilities = calculateTotal(props.liabilities, 'amount')
    return totalAssets - totalLiabilities
})

// Report header data for exports
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Balance Sheet Report',
        outletName: props.selectedBranchName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || 'N/A'
        headerData.address = props.selectedBranch.address || 'N/A'
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:headerData', newVal)
}, { immediate: true })
</script>

<style lang="scss" scoped>
.balance-sheet-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
.summary-row {
    background-color: rgba(var(--v-theme-primary), 0.05);
    border-top: 2px solid rgb(var(--v-theme-primary));
    
    td {
        padding: 16px 12px;
        border-top: 2px solid rgb(var(--v-theme-primary));
    }
}

.net-worth-card {
    background: linear-gradient(135deg, rgba(var(--v-theme-primary), 0.05) 0%, rgba(var(--v-theme-surface), 1) 100%);
    border: 2px solid rgb(var(--v-theme-primary));
}
</style>

