<template>
    <div class="profit-loss-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Outlet: {{ reportHeaderData.outletName }}
                            </div>
                            <div v-if="reportHeaderData.phone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.phone }}
                            </div>
                            <div v-if="reportHeaderData.address" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.address }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Date Range: {{ reportHeaderData.dateRange }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis mt-2">
                                Costing Method: {{ reportHeaderData.costingMethod }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Profit & Loss Table -->
                <VTable class="profit-loss-table">
                    <tbody>
                        <!-- 1. Total Sales (Paid & Unpaid) (Incl. Tax & Discount) -->
                        <tr>
                            <td class="font-weight-medium">1.</td>
                            <td class="font-weight-medium">Total Sales (Paid & Unpaid) (Incl. Tax & Discount)</td>
                            <td class="text-right">
                                {{ formatAmount(reportData.total_sales || 0) }}
                            </td>
                        </tr>

                        <!-- 2. Total Cost of Sale -->
                        <tr>
                            <td class="font-weight-medium">2.</td>
                            <td class="font-weight-medium">Total Cost of Sale</td>
                            <td class="text-right">
                                {{ formatAmount(reportData.total_cost_of_sale || 0) }}
                            </td>
                        </tr>

                        <!-- 3. Tax -->
                        <tr>
                            <td class="font-weight-medium">3.</td>
                            <td class="font-weight-medium">Tax</td>
                            <td class="text-right">
                                {{ formatAmount(reportData.tax || 0) }}
                            </td>
                        </tr>

                        <!-- 4. Discount -->
                        <tr>
                            <td class="font-weight-medium">4.</td>
                            <td class="font-weight-medium">Discount</td>
                            <td class="text-right">
                                {{ formatAmount(reportData.discount || 0) }}
                            </td>
                        </tr>

                        <tr>
                            <td class="font-weight-medium">5.</td>
                            <td class="font-weight-medium">Tips</td>
                            <td class="text-right">
                                {{ formatAmount(reportData.total_tips || 0) }}
                            </td>
                        </tr>

                        <tr>
                            <td class="font-weight-medium">6.</td>
                            <td class="font-weight-medium">Delivery Charge</td>
                            <td class="text-right">
                                {{ formatAmount(reportData.delivery_charge || 0) }}
                            </td>
                        </tr>

                        <tr class="gross-profit-row">
                            <td class="font-weight-bold">7.</td>
                            <td class="font-weight-bold">
                                Gross Profit (1) - (2+3+4+5+6)
                            </td>
                            <td class="text-right">
                                {{ formatAmount(reportData.gross_profit || 0) }}
                            </td>
                        </tr>


                        <tr>
                            <td class="font-weight-medium">8.</td>
                            <td class="font-weight-medium">Total Salaries</td>
                            <td class="text-right">
                                {{ formatAmount(reportData.total_salaries || 0) }}
                            </td>
                        </tr>

                        <!-- 7. Expense -->
                        <tr>
                            <td class="font-weight-medium">9.</td>
                            <td class="font-weight-medium">Expense</td>
                            <td class="text-right">
                                {{ formatAmount(reportData.expense || 0) }}
                            </td>
                        </tr>

                        <!-- 8. Net Profit (5) - (6+7) -->
                        <tr class="net-profit-row">
                            <td class="font-weight-bold">10.</td>
                            <td class="font-weight-bold">
                                Net Profit (7) - (8+9)
                            </td>
                            <td class="text-right">
                                {{ formatAmount(reportData.net_profit || 0) }}
                            </td>
                        </tr>
                    </tbody>
                </VTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch, onMounted } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'

const { formatDate, formatAmount, formatNumber, formatNumberPrecision, formatDateWithTime, fetchCompanySettings } = useCompanyFormatters()
const { userData } = useUserData()

onMounted(async () => {
    await fetchCompanySettings()
})

const props = defineProps({
    reportData: {
        type: Object,
        default: () => ({})
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    branches: {
        type: Array,
        default: () => []
    },
    selectedCostingMethod: {
        type: String,
        default: 'Last Purchase Price'
    },
    isLoading: {
        type: Boolean,
        default: false
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:headerData'])

// Computed properties
const grossProfitClass = computed(() => {
    const profit = props.reportData.gross_profit || 0
    return profit >= 0 ? 'text-success' : 'text-error'
})

const netProfitClass = computed(() => {
    const profit = props.reportData.net_profit || 0
    return profit >= 0 ? 'text-success' : 'text-error'
})

const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Report header data for exports
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Profit & Loss Report',
        outletName: props.selectedBranchName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value,
        costingMethod: props.selectedCostingMethod
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || 'N/A'
        headerData.address = props.selectedBranch.address || 'N/A'
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:headerData', newVal)
}, { immediate: true })

</script>

<style lang="scss" scoped>
.profit-loss-report-table {
    .profit-loss-table {
        .gross-profit-row,
        .net-profit-row {
            background-color: rgba(var(--v-theme-primary), 0.1);
            
            td {
                border-top: 2px solid rgb(var(--v-theme-primary));
                border-bottom: 2px solid rgb(var(--v-theme-primary));
            }
        }
        
        td {
            padding: 12px 16px;
            border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.12);
            
            &:first-child {
                width: 40px;
                text-align: center;
            }
            
            &:nth-child(2) {
                width: auto;
            }
            
            &:last-child {
                width: 150px;
                text-align: right;
            }
        }
    }
}
</style>
