<template>
    <div class="salary-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Outlet: {{ reportHeaderData.outletName }}
                            </div>
                            <div v-if="reportHeaderData.phone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.phone }}
                            </div>
                            <div v-if="reportHeaderData.address" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.address }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Date Range: {{ formatDateRange(dateFrom, dateTo) }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Salary Table -->
                <VDataTable
                    :items="salaries"
                    :headers="exportHeaders"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                    :items-per-page="-1"

                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                No salary records found with current filters
                            </div>
                        </div>
                    </template>

                    <!-- Date formatting -->
                    <template #item.generated_date="{ item }">
                        <span class="font-weight-medium">
                            {{ formatDate(item.generated_date) }}
                        </span>
                    </template>
                    <!-- Month-Year formatting -->
                    <template #item.month="{ item }">
                        <span class="font-weight-medium">
                            {{ (item.month) }}
                        </span>
                    </template>
                    

                    <!-- Branch name -->
                    <template #item.branch.branch_name="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.branch?.branch_name || 'N/A' }}
                        </span>
                    </template>

                    <!-- Total amount -->
                    <template #item.total_amount="{ item }">
                        <span class="font-weight-medium">
                            {{ formatAmount(item.total_amount) }}
                        </span>
                    </template>

                    <!-- User name -->
                    <template #item.user.name="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.user?.name || 'N/A' }}
                        </span>
                    </template>

                    <!-- Summary Row -->
                    <template #body.append>
                        <tr>
                            <td></td>
                            <td></td>
                            <td class="text-h6 font-weight-bold text-end">
                                Total:
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ formatAmount(calculateTotal('total_amount')) }}
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                    </template>
                    
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'

const { formatDate, formatAmount, formatDateWithTime } = useCompanyFormatters()
const { userData } = useUserData()

const props = defineProps({
    salaries: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    selectedEmployeeName: {
        type: String,
        default: 'All Employees'
    },
    isLoading: {
        type: Boolean,
        default: false
    },  
    exportHeaders: {
        type: Array,
        default: () => []
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:headerData'])

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Helper function for date range
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

// Report header data for exports
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Salary Report',
        outletName: props.selectedBranchName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || null
        headerData.address = props.selectedBranch.address || null
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:headerData', newVal)
}, { immediate: true })



// Helper functions (formatDateRange moved above)


const calculateTotal = (field) => {
    return props.salaries.reduce((sum, item) => {
        return sum + (parseFloat(item[field]) || 0)
    }, 0)
}

</script>

<style lang="scss" scoped>
.salary-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
</style>
