<template>
    <div class="salary-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="d-flex justify-space-between align-center mb-6">
                    <div>
                        <h4 class="text-h4 mb-2">Salary Report</h4>
                        <div class="text-body-1 text-medium-emphasis">
                            Date Range: {{ formatDateRange(dateFrom, dateTo) }}
                        </div>
                        <div class="text-body-1 text-medium-emphasis">
                            Outlet: {{ selectedBranchName }}
                        </div>
                    </div>
                </div>

                <!-- Salary Table -->
                <VDataTable
                    :items="salaries"
                    :headers="headers"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                No salary records found with current filters
                            </div>
                        </div>
                    </template>

                    <!-- Date formatting -->
                    <template #item.generated_date="{ item }">
                        <span class="font-weight-medium">
                            {{ formatDate(item.generated_date) }}
                        </span>
                    </template>
                    <!-- Month-Year formatting -->
                    <template #item.month="{ item }">
                        <span class="font-weight-medium">
                            {{ getMonthName(item.month) }},{{ item.year }}
                        </span>
                    </template>
                    

                    <!-- Branch name -->
                    <template #item.branch.name="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.branch?.branch_name || 'N/A' }}
                        </span>
                    </template>

                    <!-- Total amount -->
                    <template #item.total_amount="{ item }">
                        <span class="font-weight-medium text-success">
                            {{ formatAmount(item.total_amount) }}
                        </span>
                    </template>

                    <!-- User name -->
                    <template #item.user.name="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.user?.name || 'N/A' }}
                        </span>
                    </template>

                    
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
const { formatDate, formatAmount } = useCompanyFormatters()

// Month Name By Month Number

const getMonthName = (month) => {
    return monthNames[month] || month
}

const monthNames = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}

const props = defineProps({
    salaries: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    selectedEmployeeName: {
        type: String,
        default: 'All Employees'
    },
    isLoading: {
        type: Boolean,
        default: false
    }
})

// Table headers
const headers = [
    { title: 'Date', key: 'generated_date', sortable: true },
    { title: 'Month-Year', key: 'month', sortable: true },
    { title: 'Branch', key: 'branch.name', sortable: false },
    { title: 'Total Amount', key: 'total_amount', sortable: true },
    { title: 'Generated By', key: 'user.name', sortable: false },
]

// Helper functions
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}


</script>

<style lang="scss" scoped>
.salary-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
</style>
