<template>
    <div class="sale-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Outlet: {{ reportHeaderData.outletName }}
                            </div>
                            <div v-if="reportHeaderData.phone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.phone }}
                            </div>
                            <div v-if="reportHeaderData.address" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.address }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Date Range: {{ reportHeaderData.dateRange }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis mt-2">
                                Customer: {{ reportHeaderData.customerName }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Sale Table -->
                <VDataTable
                    :items="sales"
                    :headers="exportHeaders"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                    :items-per-page="-1"
                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                No sale records found with current filters
                            </div>
                        </div>
                    </template>

                    <!-- Sale No -->
                    <template #item.invoice_no="{ item }">
                        <span class="font-weight-medium">
                            {{ (item.reference_no) }}
                        </span>
                    </template>

                    <!-- Date formatting -->
                    <template #item.order_date="{ item }">
                        <span class="font-weight-medium">
                            {{ formatDate(item.order_date) }}
                        </span>
                    </template>

                    <!-- Customer name -->
                    <template #item.customer.name="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.customer?.name || 'Walk-in Customer' }}
                        </span>
                    </template>

                    <!-- Order From -->
                    <template #item.order_from="{ item }">
                        <VChip class="text-high-emphasis" :color="item.order_from == 'Website' ? 'primary' : 'secondary'" variant="tonal" size="small">
                            {{ item.order_from || 'POS' }}
                        </VChip>
                    </template>

                    <!-- Order Status -->
                    <template #item.order_status="{ item }">
                        <VChip 
                        :color="getOrderStatusColor(item.order_status)" 
                        variant="tonal" 
                        size="small"
                        >
                            {{ item.order_status || 'Pending' }}
                        </VChip>
                    </template>

                    <!-- Total payable -->
                    <template #item.total_payable="{ item }">
                        <span class="font-weight-medium">
                            {{ formatAmount(item.total_payable) }}
                        </span>
                    </template>

                    <!-- Total paid -->
                    <template #item.total_paid="{ item }">
                        <span class="font-weight-medium">
                            {{ formatAmount(item.total_paid) }}
                        </span>
                    </template>

                    <!-- Total due -->
                    <template #item.total_due="{ item }">
                        <span class="font-weight-medium">
                            {{ formatAmount(item.total_due) }}
                        </span>
                    </template>

                    <!-- Note truncation -->
                    <template #item.note="{ item }">
                        <span :title="item.note">
                            {{ item.note ? (item.note.length > 50 ? item.note.substring(0, 50) + '...' : item.note) : 'N/A' }}
                        </span>
                    </template>

                    <!-- Summary Row -->
                    <template #body.append>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="text-h6 font-weight-bold text-end">
                                Total Summary
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ formatAmount(calculateTotal('total_payable')) }}
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ formatAmount(calculateTotal('total_paid')) }}
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ formatAmount(calculateTotal('total_due')) }}
                            </td>
                            <td></td>
                        </tr>
                    </template>
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, ref, watch, onMounted } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'

const { formatDate, formatAmount, formatDateWithTime, fetchCompanySettings } = useCompanyFormatters()
const { userData } = useUserData()

onMounted(async () => {
    await fetchCompanySettings()
})

const getOrderStatusColor = (status) => {
    switch (status) {
        case 'Completed':
            return 'success'
        case 'Confirmed':
            return 'info'
        case 'Pending':
            return 'warning'
        case 'Cancelled':
            return 'error'
        default:
            return 'default'
    }
}

const props = defineProps({
    sales: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    selectedCustomerName: {
        type: String,
        default: 'All Customers'
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    branches: {
        type: Array,
        default: () => []
    },
    isLoading: {
        type: Boolean,
        default: false
    },
    exportHeaders: {
        type: Array,
        default: () => []
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:headerData'])

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Helper function
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

// Report header data for exports
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Sale Report',
        outletName: props.selectedBranchName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value,
        customerName: props.selectedCustomerName
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || 'N/A'
        headerData.address = props.selectedBranch.address || 'N/A'
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:headerData', newVal)
}, { immediate: true })

const calculateTotal = (field) => {
    return props.sales.reduce((sum, item) => {
        return sum + (parseFloat(item[field]) || 0)
    }, 0)
}



</script>

<style lang="scss" scoped>
.sale-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
    
    .summary-row {
        background-color: rgba(var(--v-theme-primary), 0.05);
        border-top: 2px solid rgb(var(--v-theme-primary));
        
        td {
            padding: 16px 12px;
            border-top: 2px solid rgb(var(--v-theme-primary));
        }
    }
}
</style>
