<template>
    <div class="staff-evaluation-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis mt-2">
                                Employee: {{ reportHeaderData.employeeName }}
                            </div>
                            <div v-if="reportHeaderData.employeePhone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.employeePhone }}
                            </div>
                            <div v-if="reportHeaderData.employeeAddress" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.employeeAddress }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Date Range: {{ reportHeaderData.dateRange }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Evaluation Table -->
                <VDataTable
                    :items="evaluations"
                    :headers="exportHeaders"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                    :items-per-page="-1"
                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                No evaluation records found with current filters
                            </div>
                        </div>
                    </template>

                    <!-- Staff Name with Phone -->
                    <template #[`item.employee.name`]="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.employee?.name || 'N/A' }}
                            <span v-if="item.employee?.phone" class="text-medium-emphasis">
                                ({{ item.employee.phone }})
                            </span>
                        </span>
                    </template>

                    <!-- Total Ratings -->
                    <template #[`item.total_ratings`]="{ item }">
                        <span class="font-weight-medium">
                            {{ formatNumber(item.total_ratings) }}
                        </span>
                    </template>

                    <!-- Average Rating -->
                    <template #[`item.avg_rating`]="{ item }">
                        <span class="font-weight-medium">
                            {{ item.avg_rating }}
                        </span>
                    </template>

                    <!-- Rating with Stars -->
                    <template #[`item.rating`]="{ item }">
                        <div class="d-flex align-center">
                            <VRating
                                :model-value="item.avg_rating"
                                color="warning"
                                half-increments
                                readonly
                                density="compact"
                                size="small"
                            />
                        </div>
                    </template>

                    <!-- Summary Row -->
                    <template #body.append>

                        <tr>
                            <td class="text-h6 font-weight-bold text-end">
                                Summary
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ formatNumber(calculateTotal('total_ratings')) }}
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ calculateAvgRating() }}
                            </td>
                            <td></td>
                        </tr>
                    </template>
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'

const { formatDate, formatNumber, formatDateWithTime } = useCompanyFormatters()
const { userData } = useUserData()

const props = defineProps({
    evaluations: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    selectedEmployeeName: {
        type: String,
        default: 'All Employees'
    },
    selectedEmployeePhone: {
        type: String,
        default: 'N/A'
    },
    selectedEmployeeAddress: {
        type: String,
        default: 'N/A'
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    isLoading: {
        type: Boolean,
        default: false
    },
    exportHeaders: {
        type: Array,
        default: () => []
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:header-data'])

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Helper functions
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

// Report header data for exports
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Staff Evaluation Report',
        outletName: props.selectedBranchName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value,
        employeeName: props.selectedEmployeeName,
        employeePhone: props.selectedEmployeePhone,
        employeeAddress: props.selectedEmployeeAddress
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || 'N/A'
        headerData.address = props.selectedBranch.address || 'N/A'
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:header-data', newVal)
}, { immediate: true })

const calculateTotal = (field) => {
    return props.evaluations.reduce((sum, item) => {
        return sum + (parseFloat(item[field]) || 0)
    }, 0)
}

const calculateAvgRating = () => {
    if (props.evaluations.length === 0) return '0.00'
    const totalAvg = props.evaluations.reduce((sum, item) => {
        return sum + (parseFloat(item.avg_rating) || 0)
    }, 0)
    return (totalAvg / props.evaluations.length).toFixed(2)
}
</script>

<style lang="scss" scoped>
.staff-evaluation-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
.summary-row {
    background-color: rgba(var(--v-theme-primary), 0.05);
    border-top: 2px solid rgb(var(--v-theme-primary));
    
    td {
        padding: 16px 12px;
        border-top: 2px solid rgb(var(--v-theme-primary));
    }
}
</style>

