<template>
    <div class="staff-evaluation-details-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Employee: {{ reportHeaderData.employeeName }}
                            </div>
                            <div v-if="reportHeaderData.employeePhone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.employeePhone }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Date Range: {{ reportHeaderData.dateRange }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Evaluation Details Table -->
                <VDataTable
                    :items="evaluationDetails"
                    :headers="exportHeaders"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                    :items-per-page="-1"
                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                No evaluation records found with current filters
                            </div>
                        </div>
                    </template>

                    <!-- Staff Name with Phone -->
                    <template #[`item.employee.name`]="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.employee?.name || 'N/A' }}
                            <span v-if="item.employee?.phone" class="text-medium-emphasis">
                                ({{ item.employee.phone }})
                            </span>
                        </span>
                    </template>

                    <!-- Customer Name with Phone -->
                    <template #[`item.customer.name`]="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.customer?.name || 'N/A' }}
                            <span v-if="item.customer?.phone" class="text-medium-emphasis">
                                ({{ item.customer.phone }})
                            </span>
                        </span>
                    </template>

                    <!-- Item Name -->
                    <template #[`item.item.name`]="{ item }">
                        <VChip 
                            color="primary" 
                            variant="tonal" 
                            size="small"
                        >
                            {{ item.item?.name || 'N/A' }}
                        </VChip>
                    </template>

                    <!-- Rating Number -->
                    <template #[`item.rating_number`]="{ item }">
                        <span class="font-weight-medium">
                            {{ item.rating }}
                        </span>
                    </template>

                    <!-- Rating with Stars (Visual Rating) -->
                    <template #[`item.rating`]="{ item }">
                        <div class="d-flex align-center">
                            <VRating
                                :model-value="item.rating"
                                color="warning"
                                half-increments
                                readonly
                                density="compact"
                                size="small"
                            />
                        </div>
                    </template>

                    <!-- Created Date formatting -->
                    <template #[`item.created_at`]="{ item }">
                        <span class="font-weight-medium">
                            {{ formatDate(item.rating_date) }}
                        </span>
                    </template>

                    <!-- Summary Row -->
                    <template #body.append>
                        <tr>
                            <td></td>
                            <td class="text-h6 font-weight-bold text-end">
                                Summary
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ evaluationDetails.length }}
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ calculateAvgRating() }}
                            </td>
                            <td></td>
                            <td></td>
                        </tr>
                    </template>
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch, onMounted } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'

const { formatDate, formatDateWithTime, fetchCompanySettings } = useCompanyFormatters()
const { userData } = useUserData()

onMounted(async () => {
    await fetchCompanySettings()
})

const props = defineProps({
    evaluationDetails: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedEmployeeName: {
        type: String,
        default: 'All Employees'
    },
    selectedEmployee: {
        type: Object,
        default: null
    },
    isLoading: {
        type: Boolean,
        default: false
    },
    exportHeaders: {
        type: Array,
        default: () => []
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:header-data'])

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Helper functions
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

// Report header data for exports
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Staff Evaluation Details Report',
        employeeName: props.selectedEmployeeName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value
    }
    
    // Only include employee phone if a specific employee is selected
    if (props.selectedEmployee) {
        headerData.employeePhone = props.selectedEmployee.phone || null
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:header-data', newVal)
}, { immediate: true })

const calculateAvgRating = () => {
    if (props.evaluationDetails.length === 0) return '0.00'
    const totalRating = props.evaluationDetails.reduce((sum, item) => {
        return sum + (parseFloat(item.rating) || 0)
    }, 0)
    return (totalRating / props.evaluationDetails.length).toFixed(2)
}
</script>

<style lang="scss" scoped>
.staff-evaluation-details-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
.summary-row {
    background-color: rgba(var(--v-theme-primary), 0.05);
    border-top: 2px solid rgb(var(--v-theme-primary));
    
    td {
        padding: 16px 12px;
        border-top: 2px solid rgb(var(--v-theme-primary));
    }
}
</style>

