<template>
    <div class="staff-payout-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Outlet: {{ reportHeaderData.outletName }}
                            </div>
                            <div v-if="reportHeaderData.phone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.phone }}
                            </div>
                            <div v-if="reportHeaderData.address" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.address }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Date Range: {{ reportHeaderData.dateRange }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis mt-2">
                                Employee: {{ reportHeaderData.employeeName }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Payout Table -->
                <VDataTable
                    :items="payouts"
                    :headers="exportHeaders"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                    :items-per-page="-1"
                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                No payout records found with current filters
                            </div>
                        </div>
                    </template>

                    <!-- Date formatting -->
                    <template #[`item.date`]="{ item }">
                        <span class="font-weight-medium">
                            {{ formatDate(item.date) }}
                        </span>
                    </template>

                    <!-- Reference number -->
                    <template #[`item.reference_no`]="{ item }">
                        <span class="font-weight-medium">
                            {{ item.reference_no || 'N/A' }}
                        </span>
                    </template>

                    <!-- Employee name -->
                    <template #[`item.employee.name`]="{ item }">
                        <span class="text-high-emphasis">
                            {{ item.employee?.name || 'N/A' }}
                        </span>
                    </template>

                    <!-- Payment method name -->
                    <template #[`item.payment_method.name`]="{ item }">
                        <VChip 
                            :color="item.payment_method?.name ? 'primary' : 'default'" 
                            variant="tonal" 
                            size="small"
                        >
                            {{ item.payment_method?.name || 'N/A' }}
                        </VChip>
                    </template>

                    <!-- Amount formatting -->
                    <template #[`item.amount`]="{ item }">
                        <span class="font-weight-medium">
                            {{ formatAmount(item.amount) }}
                        </span>
                    </template>

                    <!-- Note truncation -->
                    <template #[`item.note`]="{ item }">
                        <span :title="item.note">
                            {{ item.note ? (item.note.length > 50 ? item.note.substring(0, 50) + '...' : item.note) : 'N/A' }}
                        </span>
                    </template>

                    <!-- Summary Row -->
                    <template #body.append>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="text-h6 font-weight-bold text-end">
                                Summary
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ formatAmount(calculateTotal('amount')) }}
                            </td>
                            <td></td>
                        </tr>
                    </template>
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch, onMounted } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'

const { formatDate, formatAmount, formatDateWithTime, fetchCompanySettings } = useCompanyFormatters()
const { userData } = useUserData()

onMounted(async () => {
    await fetchCompanySettings()
})

const props = defineProps({
    payouts: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    selectedEmployeeName: {
        type: String,
        default: 'All Employees'
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    isLoading: {
        type: Boolean,
        default: false
    },
    exportHeaders: {
        type: Array,
        default: () => []
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:header-data'])

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Helper functions
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

// Report header data for exports
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Staff Payout Report',
        outletName: props.selectedBranchName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value,
        employeeName: props.selectedEmployeeName
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || 'N/A'
        headerData.address = props.selectedBranch.address || 'N/A'
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:header-data', newVal)
}, { immediate: true })

const calculateTotal = (field) => {
    return props.payouts.reduce((sum, item) => {
        return sum + (parseFloat(item[field]) || 0)
    }, 0)
}
</script>

<style lang="scss" scoped>
.staff-payout-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
.summary-row {
    background-color: rgba(var(--v-theme-primary), 0.05);
    border-top: 2px solid rgb(var(--v-theme-primary));
    
    td {
        padding: 16px 12px;
        border-top: 2px solid rgb(var(--v-theme-primary));
    }
}
</style>
