<template>
    <div class="transaction-history-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header (matches Account Statement template structure) -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Outlet: {{ reportHeaderData.outletName }}
                            </div>
                            <div v-if="reportHeaderData.phone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.phone }}
                            </div>
                            <div v-if="reportHeaderData.address" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.address }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Date Range: {{ reportHeaderData.dateRange }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Payment Account: {{ reportHeaderData.paymentAccountName }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Transaction History Table -->
                <VDataTable
                    :items="transactions"
                    :headers="exportHeaders"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                    :items-per-page="-1"
                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                {{ !selectedPaymentMethodName || selectedPaymentMethodName === 'All Payment Accounts' 
                                    ? 'Please select a payment account to view transactions' 
                                    : 'No transactions found with current filters' }}
                            </div>
                        </div>
                    </template>

                    <!-- SN -->
                    <template #item.sn="{ item }">
                        <span class="font-weight-medium">
                            {{ item.sn }}
                        </span>
                    </template>

                    <!-- Date -->
                    <template #item.date="{ item }">
                        {{ formatDate(item.date) }}
                    </template>

                    <!-- Reference No -->
                    <template #item.reference_no="{ item }">
                        <span>
                            {{ item.reference_no }}
                        </span>
                    </template>

                    <!-- Type -->
                    <template #item.type="{ item }">
                        <span
                        >
                            {{ item.type }}
                        </span>
                    </template>

                    <!-- Payment Account -->
                    <template #item.payment_account="{ item }">
                        {{ item.payment_account }}
                    </template>

                    <!-- Amount -->
                    <template #item.amount="{ item }">
                        <span>
                            {{ formatAmount(item.amount) }}
                        </span>
                    </template>

                    <!-- Added By -->
                    <template #item.added_by="{ item }">
                        {{ item.added_by }}
                    </template>

                    <!-- Added Date Time -->
                    <template #item.added_date_time="{ item }">
                        {{ item.added_date_time }}
                    </template>

                    <!-- Summary Row as Data Table Footer (matches Account Balance/Statement) -->
                    <template #body.append>
                        <tr>
                            <td class="text-h6 font-weight-bold">
                                <!-- Empty for SN column -->
                            </td>
                            <td class="text-h6 font-weight-bold">
                                <!-- Empty for Date column -->
                            </td>
                            <td class="text-h6 font-weight-bold">
                                <!-- Empty for Reference No column -->
                            </td>
                            <td class="text-h6 font-weight-bold">
                                <!-- Empty for Type column -->
                            </td>
                            <td class="text-h6 font-weight-bold text-end">
                                Total Amount:
                            </td>
                            <td class="text-h6 font-weight-bold">
                                 {{ formatAmount(calculateTotal('amount')) }}
                            </td>
                            <td class="text-h6 font-weight-bold">
                                <!-- Empty for Added By column -->
                            </td>
                            <td class="text-h6 font-weight-bold">
                                <!-- Empty for Added Date Time column -->
                            </td>
                        </tr>
                    </template>
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'

const { formatDate, formatAmount, formatDateWithTime } = useCompanyFormatters()
const { userData } = useUserData()

const props = defineProps({
    transactions: {
        type: Array,
        default: () => []
    },
    dateFrom: {
        type: String,
        default: ''
    },
    dateTo: {
        type: String,
        default: ''
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    selectedPaymentMethodName: {
        type: String,
        default: 'All Payment Accounts'
    },
    isLoading: {
        type: Boolean,
        default: false
    },
    exportHeaders: {
        type: Array,
        default: () => []
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:headerData'])

// Helper functions
const formatDateRange = (from, to) => {
    if (!from && !to) return 'All Time'
    if (!from) return `Until ${formatDate(to)}`
    if (!to) return `From ${formatDate(from)}`
    return `${formatDate(from)} - ${formatDate(to)}`
}

const calculateTotal = (field) => {
    return props.transactions.reduce((sum, item) => {
        return sum + (parseFloat(item[field]) || 0)
    }, 0)
}

const getTypeColor = (type) => {
    const typeColors = {
        'Sale': 'success',
        'Customer Receive': 'info',
        'Deposit': 'success',
        'Purchase': 'warning',
        'Supplier Payment': 'warning',
        'Expense': 'error',
        'Staff Payment': 'error',
        'Withdraw': 'error',
    }
    return typeColors[type] || 'default'
}

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Report header data for exports (matches Account Statement structure)
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Transaction History Report',
        outletName: props.selectedBranchName,
        dateRange: formatDateRange(props.dateFrom, props.dateTo),
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value,
        paymentAccountName: props.selectedPaymentMethodName
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || 'N/A'
        headerData.address = props.selectedBranch.address || 'N/A'
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:headerData', newVal)
}, { immediate: true })
</script>

<style lang="scss" scoped>
.transaction-history-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
.summary-row {
    background-color: rgba(var(--v-theme-primary), 0.05);
    border-top: 2px solid rgb(var(--v-theme-primary));
    
    td {
        padding: 16px 12px;
        border-top: 2px solid rgb(var(--v-theme-primary));
    }
}
</style>

