<template>
    <div class="trial-balance-report-table">
        <VCard>
            <VCardText>
                <!-- Report Header -->
                <div class="report-header">
                    <h4 class="text-h4 mb-2 text-center">{{ reportHeaderData.reportTitle }}</h4>
                    <div class="d-flex justify-space-between align-center mb-6">
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Outlet: {{ reportHeaderData.outletName }}
                            </div>
                            <div v-if="reportHeaderData.phone" class="text-body-1 text-medium-emphasis">
                                Phone: {{ reportHeaderData.phone }}
                            </div>
                            <div v-if="reportHeaderData.address" class="text-body-1 text-medium-emphasis">
                                Address: {{ reportHeaderData.address }}
                            </div>
                        </div>
                        <div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated On: {{ reportHeaderData.generatedOn }}
                            </div>
                            <div class="text-body-1 text-medium-emphasis">
                                Generated By: {{ reportHeaderData.generatedBy }}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Trial Balance Table -->
                <VDataTable
                    :items="trialBalance"
                    :headers="exportHeaders"
                    class="text-no-wrap"
                    :loading="isLoading"
                    hide-default-footer
                    :items-per-page="-1"
                >
                    <!-- Loading state -->
                    <template #loading>
                        <VSkeletonLoader type="table-row" :rows="10" />
                    </template>

                    <!-- No data state -->
                    <template #no-data>
                        <div class="d-flex align-center justify-center pa-4">
                            <VIcon icon="tabler-alert-circle" class="me-2" />
                            <div>
                                No trial balance records found with current filters
                            </div>
                        </div>
                    </template>

                    <!-- SN -->
                    <template #item.sn="{ item }">
                        <span class="font-weight-medium">
                            {{ item.sn }}
                        </span>
                    </template>

                    <!-- Title -->
                    <template #item.title="{ item }">
                        <span class="text-high-emphasis font-weight-medium">
                            {{ item.title }}
                        </span>
                    </template>

                    <!-- Debit formatting -->
                    <template #item.debit="{ item }">
                        <span 
                            v-if="item.debit > 0"
                            class="font-weight-bold"
                        >
                            {{ formatAmount(item.debit) }}
                        </span>
                        <span v-else class="text-medium-emphasis">-</span>
                    </template>

                    <!-- Credit formatting -->
                    <template #item.credit="{ item }">
                        <span 
                            v-if="item.credit > 0"
                            class="font-weight-bold"
                        >
                            {{ formatAmount(item.credit) }}
                        </span>
                        <span v-else class="text-medium-emphasis">-</span>
                    </template>

                    <!-- Summary Row as Data Table Footer -->
                    <template #body.append>
                        <tr>
                            <td class="text-h6 font-weight-bold">
                                <!-- Empty for SN column -->
                            </td>
                            <td class="text-end text-h6 font-weight-bold">                                   
                                Total:
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ formatAmount(calculateTotal('debit')) }}
                            </td>
                            <td class="text-h6 font-weight-bold">
                                {{ formatAmount(calculateTotal('credit')) }}
                            </td>
                        </tr>
                    </template>
                </VDataTable>
            </VCardText>
        </VCard>
    </div>
</template>

<script setup>
import { computed, watch } from 'vue'
import { useCompanyFormatters } from '@/composables/useCompanyFormatters'
import { useUserData } from '@/composables/useUserData'
import { useCompanySettings } from '@/composables/useCompanySettings'

const { formatDate, formatAmount, formatDateWithTime } = useCompanyFormatters()
const { userData } = useUserData()
const { companySettings } = useCompanySettings()

const props = defineProps({
    trialBalance: {
        type: Array,
        default: () => []
    },
    selectedBranch: {
        type: Object,
        default: null
    },
    selectedBranchName: {
        type: String,
        default: 'All Outlets'
    },
    isLoading: {
        type: Boolean,
        default: false
    },
    exportHeaders: {
        type: Array,
        default: () => []
    }
})

// Define emits for passing header data to parent
const emit = defineEmits(['update:headerData'])

// Get current date and time
const currentDateTime = computed(() => {
    const date = formatDateWithTime(new Date().toISOString())
    return `${date}`
})

// Get current user name
const currentUserName = computed(() => userData.value?.name || 'N/A')

// Report header data for exports
const reportHeaderData = computed(() => {
    const headerData = {
        reportTitle: 'Trial Balance Report',
        outletName: props.selectedBranchName,
        generatedOn: currentDateTime.value,
        generatedBy: currentUserName.value
    }
    
    // Only include phone and address if a specific branch is selected
    if (props.selectedBranch) {
        headerData.phone = props.selectedBranch.phone || 'N/A'
        headerData.address = props.selectedBranch.address || 'N/A'
    }
    
    return headerData
})

// Emit header data whenever it changes
watch(reportHeaderData, (newVal) => {
    emit('update:headerData', newVal)
}, { immediate: true })

// Helper functions
const calculateTotal = (field) => {
    return props.trialBalance.reduce((sum, item) => {
        return sum + (parseFloat(item[field]) || 0)
    }, 0)
}

const difference = computed(() => {
    return calculateTotal('debit') - calculateTotal('credit')
})
</script>

<style lang="scss" scoped>
.trial-balance-report-table {
    .v-data-table {
        .v-data-table__wrapper {
            border-radius: 8px;
        }
    }
}
.summary-row {
    background-color: rgba(var(--v-theme-primary), 0.05);
    border-top: 2px solid rgb(var(--v-theme-primary));
    
    td {
        padding: 16px 12px;
        border-top: 2px solid rgb(var(--v-theme-primary));
    }
}

.difference-row {
    background-color: rgba(var(--v-theme-warning), 0.05);
    
    td {
        padding: 16px 12px;
    }
}
</style>

