<template>
  <VMenu>
    <template #activator="{ props }">
      <VBtn
        v-bind="props"
        variant="tonal"
        color="secondary"
        prepend-icon="tabler-upload"
        :loading="isExporting"
      >
        Export
        <VIcon icon="tabler-chevron-down" class="ml-1" />
      </VBtn>
    </template>

    <VList>
      <VListItem
        prepend-icon="tabler-file-type-pdf"
        title="Export as PDF"
        @click="exportToPDF"
      />
      <VListItem
        prepend-icon="tabler-file-type-csv"
        title="Export as CSV"
        @click="exportToCSV"
      />
      <VListItem
        prepend-icon="tabler-file-spreadsheet"
        title="Export as Excel"
        @click="exportToExcel"
      />
    </VList>
  </VMenu>
</template>

<script setup>
import { ref } from 'vue'
import { toast } from 'vue3-toastify'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const props = defineProps({
  assets: {
    type: Array,
    required: true,
    default: () => []
  },
  liabilities: {
    type: Array,
    required: true,
    default: () => []
  },
  filename: {
    type: String,
    default: 'balance-sheet-report'
  },
  headerData: {
    type: Object,
    default: () => ({
      reportTitle: 'Balance Sheet Report',
      outletName: 'All Outlets',
      phone: null,
      address: null,
      dateRange: 'All Time',
      generatedOn: '',
      generatedBy: 'N/A'
    })
  },
  summaryData: {
    type: Object,
    default: null
  }
})

const isExporting = ref(false)

/* -----------------------------
   Helper: Build CSV/Excel Data
----------------------------- */
const buildExportData = () => {
  const assetsData = props.assets.map(i => ({
    SN: i.sn,
    Title: i.title,
    Amount: i.amount
  }))

  // Add totals like Step 1 (under table)
  assetsData.push({
    SN: '',
    Title: 'Total Assets',
    Amount: props.summaryData?.totalAssets || 0
  })

  const liabilitiesData = props.liabilities.map(i => ({
    SN: i.sn,
    Title: i.title,
    Amount: i.amount
  }))
  liabilitiesData.push({
    SN: '',
    Title: 'Total Liabilities',
    Amount: props.summaryData?.totalLiabilities || 0
  })
  liabilitiesData.push({
    SN: '',
    Title: 'Net Worth',
    Amount: props.summaryData?.netWorth || 0
  })

  return { assetsData, liabilitiesData }
}

/* -----------------------------
   CSV Export
----------------------------- */
const exportToCSV = () => {
  try {
    isExporting.value = true
    const { assetsData, liabilitiesData } = buildExportData()

    let csvContent = `${props.headerData.reportTitle}\n\n`
    csvContent += `Outlet: ${props.headerData.outletName}\n`
    if (props.headerData.phone) csvContent += `Phone: ${props.headerData.phone}\n`
    if (props.headerData.address) csvContent += `Address: ${props.headerData.address}\n`
    csvContent += `Date Range: ${props.headerData.dateRange}\n`
    csvContent += `Generated On: ${props.headerData.generatedOn}\n`
    csvContent += `Generated By: ${props.headerData.generatedBy}\n\n`

    // Assets section
    csvContent += 'ASSETS\nSN,Title,Amount\n'
    assetsData.forEach(row => {
      csvContent += `${row.SN},${row.Title},${row.Amount}\n`
    })
    csvContent += '\n'

    // Liabilities section
    csvContent += 'LIABILITIES\nSN,Title,Amount\n'
    liabilitiesData.forEach(row => {
      csvContent += `${row.SN},${row.Title},${row.Amount}\n`
    })

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const link = document.createElement('a')
    const url = URL.createObjectURL(blob)
    link.href = url
    link.download = `${props.filename}.csv`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    toast('CSV exported successfully', { type: 'success' })
  } catch (err) {
    console.error(err)
    toast('Failed to export CSV', { type: 'error' })
  } finally {
    isExporting.value = false
  }
}

/* -----------------------------
   Excel Export
----------------------------- */
const exportToExcel = async () => {
  try {
    isExporting.value = true
    const XLSX = await import('xlsx')
    const { assetsData, liabilitiesData } = buildExportData()

    const headerInfo = [
      [props.headerData.reportTitle],
      [],
      ['Outlet:', props.headerData.outletName],
    ]

    if (props.headerData.phone) headerInfo.push(['Phone:', props.headerData.phone])
    if (props.headerData.address) headerInfo.push(['Address:', props.headerData.address])

    headerInfo.push(
      ['Generated On:', props.headerData.generatedOn],
      ['Generated By:', props.headerData.generatedBy],
      []
    )

    const ws = XLSX.utils.aoa_to_sheet(headerInfo)

    // Add sections
    XLSX.utils.sheet_add_aoa(ws, [['ASSETS']], { origin: -1 })
    XLSX.utils.sheet_add_json(ws, assetsData, { origin: -1, skipHeader: false })
    XLSX.utils.sheet_add_aoa(ws, [['']], { origin: -1 })
    XLSX.utils.sheet_add_aoa(ws, [['LIABILITIES']], { origin: -1 })
    XLSX.utils.sheet_add_json(ws, liabilitiesData, { origin: -1, skipHeader: false })

    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, 'Balance Sheet')
    XLSX.writeFile(wb, `${props.filename}.xlsx`)
    toast('Excel file exported successfully', { type: 'success' })
  } catch (err) {
    console.error(err)
    toast('Failed to export Excel file', { type: 'error' })
  } finally {
    isExporting.value = false
  }
}

/* -----------------------------
   PDF Export
----------------------------- */
const exportToPDF = () => {
  try {
    isExporting.value = true
    const doc = new jsPDF('p')
    const pageWidth = doc.internal.pageSize.getWidth()
    let currentY = 15

    // Title
    doc.setFontSize(16)
    doc.setFont(undefined, 'bold')
    doc.text(props.headerData.reportTitle, pageWidth / 2, currentY, { align: 'center' })
    currentY += 10

    doc.setFontSize(10)
    doc.setFont(undefined, 'normal')
    doc.text(`Outlet: ${props.headerData.outletName}`, 14, currentY)
    currentY += 6
    if (props.headerData.phone) doc.text(`Phone: ${props.headerData.phone}`, 14, currentY), currentY += 6
    if (props.headerData.address) doc.text(`Address: ${props.headerData.address}`, 14, currentY), currentY += 6
    currentY += 6
    doc.text(`Generated On: ${props.headerData.generatedOn}`, pageWidth - 14, currentY - 6, { align: 'right' })
    doc.text(`Generated By: ${props.headerData.generatedBy}`, pageWidth - 14, currentY, { align: 'right' })
    currentY += 10

    // ----------------------
    // ASSETS TABLE
    // ----------------------
    doc.setFontSize(12)
    doc.setFont(undefined, 'bold')
    doc.text('ASSETS', 14, currentY)
    currentY += 5

    autoTable(doc, {
      startY: currentY,
      head: [['SN', 'Title', 'Amount']],
      body: props.assets.map(r => [r.sn, r.title, r.amount]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [40, 167, 69], textColor: 255 },
    })

    const assetsEndY = doc.lastAutoTable.finalY + 6
    doc.setFontSize(10)
    doc.setFont(undefined, 'bold')
    doc.text('Total Assets', 40, assetsEndY) // under Title column
    doc.text(`${props.summaryData?.totalAssets || 0}`, pageWidth - 65, assetsEndY, { align: 'right' }) // under Amount column

    // ----------------------
    // LIABILITIES TABLE
    // ----------------------
    doc.setFontSize(12)
    doc.setFont(undefined, 'bold')
    doc.text('LIABILITIES', 14, assetsEndY + 12)

    autoTable(doc, {
      startY: assetsEndY + 17,
      head: [['SN', 'Title', 'Amount']],
      body: props.liabilities.map(r => [r.sn, r.title, r.amount]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [220, 53, 69], textColor: 255 },
    })

    const liabilitiesEndY = doc.lastAutoTable.finalY + 6
    doc.setFontSize(10)
    doc.setFont(undefined, 'bold')
    doc.text('Total Liabilities', 40, liabilitiesEndY) // under Title
    doc.text(`${props.summaryData?.totalLiabilities || 0}`, pageWidth - 65, liabilitiesEndY, { align: 'right' }) // under Amount
    doc.text('Net Worth', 40, liabilitiesEndY + 6) // under Title
    doc.text(`${props.summaryData?.netWorth || 0}`, pageWidth - 65, liabilitiesEndY + 6, { align: 'right' }) // under Amount

    doc.save(`${props.filename}.pdf`)
    toast('PDF exported successfully', { type: 'success' })
  } catch (err) {
    console.error(err)
    toast('Failed to export PDF', { type: 'error' })
  } finally {
    isExporting.value = false
  }
}
</script>