<template>
  <VMenu>
    <template #activator="{ props }">
      <VBtn 
        v-bind="props"
        variant="tonal" 
        color="secondary" 
        prepend-icon="tabler-upload"
        :loading="isExporting"
      >
        Export
        <VIcon icon="tabler-chevron-down" class="ml-1" />
      </VBtn>
    </template>

    <VList>
      <VListItem
        prepend-icon="tabler-file-type-pdf"
        title="Export as PDF"
        @click="exportToPDF"
      />
      <VListItem
        prepend-icon="tabler-file-type-csv"
        title="Export as CSV"
        @click="exportToCSV"
      />
      <VListItem
        prepend-icon="tabler-file-spreadsheet"
        title="Export as Excel"
        @click="exportToExcel"
      />
    </VList>
  </VMenu>
</template>

<script setup>
import { ref } from 'vue'
import { toast } from 'vue3-toastify'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const props = defineProps({
  data: {
    type: Array,
    required: true,
    default: () => []
  },
  headers: {
    type: Array,
    required: true,
    default: () => []
  },
  filename: {
    type: String,
    default: 'stock-report'
  },
  title: {
    type: String,
    default: 'Stock Report'
  },
  headerData: {
    type: Object,
    default: () => ({
      reportTitle: 'Stock Report',
      itemName: null,
      categoryName: null,
      generatedOn: '',
      generatedBy: 'N/A',
      supplierName: 'All Suppliers'
    })
  },
  summaryData: {
    type: Object,
    default: null
  }
})

const isExporting = ref(false)

// Helper function to get nested property value
const getNestedValue = (obj, path) => {
  return path.split('.').reduce((o, p) => o && o[p], obj)
}

// Helper function to format data for export
const formatDataForExport = () => {
  const exportHeaders = props.headers
    .filter(header => header.key !== 'actions')
    .map(header => header.title)

  const exportData = props.data.map(item => {
    const row = {}
    props.headers.forEach(header => {
      if (header.key !== 'actions') {
        let value = getNestedValue(item, header.key)
        
        // Handle special formatting
        if (header.key === 'date' && value) {
          value = new Date(value).toLocaleDateString()
        } else if (header.key.includes('employee') && typeof value === 'object' && value?.name) {
          value = value.name
        } else if (value === null || value === undefined) {
          value = 'N/A'
        }
        
        row[header.title] = value
      }
    })
    return row
  })

  // Add summary row if summaryData is provided
  if (props.summaryData) {
    const summaryRow = {}
    props.headers.forEach(header => {
      if (header.key !== 'actions') {
        if (header.key === 'category.name') {
          summaryRow[header.title] = 'Summary:'
        } else if (header.key === 'stock') {
          summaryRow[header.title] = props.summaryData?.total_stock || 0
        } else if (header.key === 'total_price') {
          summaryRow[header.title] = props.summaryData?.total_stock_value || 0
        } else {
          summaryRow[header.title] = ''
        }
      }
    })
    exportData.push(summaryRow)
  }

  return { headers: exportHeaders, data: exportData }
}

// Export to CSV
const exportToCSV = () => {
  try {
    isExporting.value = true
    const { headers, data } = formatDataForExport()

    // Create header info rows
    const headerInfo = [
      props.headerData.reportTitle,
      ''
    ]
    
    // Add item name only if filtered
    if (props.headerData.itemName) {
      headerInfo.push(`Item: ${props.headerData.itemName}`)
    }
    
    // Add category name only if filtered
    if (props.headerData.categoryName) {
      headerInfo.push(`Category: ${props.headerData.categoryName}`)
    }
    
    headerInfo.push(
      `Generated On: ${props.headerData.generatedOn}`,
      `Generated By: ${props.headerData.generatedBy}`,
      `Supplier: ${props.headerData.supplierName}`,
      '',
      ''
    )

    const csvContent = [
      ...headerInfo,
      headers.join(','),
      ...data.map(row => 
        headers.map(header => {
          const value = row[header] || ''
          // Escape quotes and wrap in quotes if contains comma
          return typeof value === 'string' && (value.includes(',') || value.includes('"'))
            ? `"${value.replace(/"/g, '""')}"`
            : value
        }).join(',')
      )
    ].join('\n')
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const link = document.createElement('a')
    const url = URL.createObjectURL(blob)
    link.setAttribute('href', url)
    link.setAttribute('download', `${props.filename}.csv`)
    link.style.visibility = 'hidden'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    
    toast('CSV exported successfully', { type: 'success' })
  } catch (error) {
    console.error('Error exporting CSV:', error)
    toast('Failed to export CSV', { type: 'error' })
  } finally {
    isExporting.value = false
  }
}

// Export to Excel
const exportToExcel = async () => {
  try {
    isExporting.value = true
    
    // Dynamic import to avoid bundling if not used
    const XLSX = await import('xlsx')
    const { headers, data } = formatDataForExport()
    
    // Create header info rows
    const headerInfo = [
      [props.headerData.reportTitle],
      []
    ]
    
    // Add item name only if filtered
    if (props.headerData.itemName) {
      headerInfo.push(['Item:', props.headerData.itemName])
    }
    
    // Add category name only if filtered
    if (props.headerData.categoryName) {
      headerInfo.push(['Category:', props.headerData.categoryName])
    }
    
    headerInfo.push(
      ['Generated On:', props.headerData.generatedOn],
      ['Generated By:', props.headerData.generatedBy],
      ['Supplier:', props.headerData.supplierName],
      []
    )
    
    // Create worksheet with header info
    const ws = XLSX.utils.aoa_to_sheet(headerInfo)
    
    // Add table headers and data
    XLSX.utils.sheet_add_json(ws, data, { 
      origin: `A${headerInfo.length + 1}`,
      skipHeader: false 
    })
    
    // Create workbook
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1')
    
    // Save file
    XLSX.writeFile(wb, `${props.filename}.xlsx`)
    
    toast('Excel file exported successfully', { type: 'success' })
  } catch (error) {
    console.error('Error exporting Excel:', error)
    toast('Failed to export Excel file. Please install xlsx package.', { type: 'error' })
  } finally {
    isExporting.value = false
  }
}

// Export to PDF
const exportToPDF = () => {
  try {
    isExporting.value = true
    const { headers, data } = formatDataForExport()
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    
    let currentY = 15
    
    // Report Title
    doc.setFontSize(16)
    doc.setFont(undefined, 'bold')
    doc.text(props.headerData.reportTitle, pageWidth / 2, 15, { align: 'center' })
    currentY += 10
    
    // Left Side - Item and Category (if filtered)
    doc.setFontSize(10)
    doc.setFont(undefined, 'normal')
    
    let leftStartY = currentY
    
    // Add item name only if filtered
    if (props.headerData.itemName) {
      doc.text(`Item: ${props.headerData.itemName}`, 14, leftStartY)
      leftStartY += 6
    }
    else {
      doc.text('Item: All Items', 14, leftStartY)
      leftStartY += 6
    }
    
    // Add category name only if filtered
    if (props.headerData.categoryName) {
      doc.text(`Category: ${props.headerData.categoryName}`, 14, leftStartY)
      leftStartY += 6
    }
    
    // Track the right side Y position
    const rightStartY = currentY
    
    // Generated Info (Right Side)
    doc.text(`Generated On: ${props.headerData.generatedOn}`, pageWidth - 14, rightStartY, { align: 'right' })
    doc.text(`Generated By: ${props.headerData.generatedBy}`, pageWidth - 14, rightStartY + 6, { align: 'right' })
    doc.text(`Supplier: ${props.headerData.supplierName}`, pageWidth - 14, rightStartY + 12, { align: 'right' })
    
    currentY = Math.max(leftStartY, rightStartY + 18)
    currentY += 4
    
    // Add table
    autoTable(doc, {
      head: [headers],
      body: data.map(row => headers.map(header => row[header] || '')),
      startY: currentY,
      styles: {
        fontSize: 8,
        cellPadding: 2
      },
      headStyles: {
        fillColor: [66, 139, 202],
        textColor: 255,
        fontStyle: 'bold'
      }
    })

    doc.save(`${props.filename}.pdf`)
    toast('PDF exported successfully', { type: 'success' })
  } catch (error) {
    console.error('Error exporting PDF:', error)
    toast('Failed to export PDF. Please install jspdf and jspdf-autotable packages.', { type: 'error' })
  } finally {
    isExporting.value = false
  }
}
</script> 
