<script setup>
import { computed } from 'vue'
import { useSalaryReport } from '@/composables/useSalaryReport'
import SalaryReportFilters from '@/components/report/SalaryReportFilters.vue'
import SalarySummaryCards from '@/components/report/SalarySummaryCards.vue'
import SalaryReportTable from '@/components/report/SalaryReportTable.vue'
import ExportTableSalaryReport from '@/components/ExportTableSalaryReport.vue'

// Use the salary report composable
const {
    // State
    salaryData,
    isLoading,
    branchId,
    employeeId,
    dateFrom,
    dateTo,
    branches,
    employees,
    
    // Methods
    resetFilters,
    
    // Computed
    salaries,
    totalSalaries
} = useSalaryReport()



// Computed properties
const selectedBranchName = computed(() => {
    if (!branchId.value) return 'All Outlets'
    const branch = branches.value.find(b => b.id == branchId.value)
    return branch?.name || 'All Outlets'
})

const selectedEmployeeName = computed(() => {
    if (!employeeId.value) return 'All Employees'
    const employee = employees.value.find(e => e.id == employeeId.value)
    return employee?.name || 'All Employees'
})

const exportHeaders = computed(() => [
    { title: 'Generated Date', key: 'generated_date', sortable: true },
    { title: 'Month-Year', key: 'month', sortable: true },
    { title: 'Branch', key: 'branch.branch_name', sortable: false },
    { title: 'Total Amount', key: 'total_amount', sortable: true },
    { title: 'Payment Account', key: 'payment_method_name', sortable: false },
    { title: 'Generated By', key: 'user.name', sortable: false },
])

const handleResetFilters = () => {
    resetFilters()
}

</script>

<template>
    <div>
        <!-- Filter Section -->
        <VCard class="mb-4">
            <VCardText>
                <SalaryReportFilters
                    v-model:date-from="dateFrom"
                    v-model:date-to="dateTo"
                    v-model:branch-id="branchId"
                    v-model:employee-id="employeeId"
                    :branches="branches"
                    :employees="employees"
                />
            </VCardText>
        </VCard>

        <!-- Summary Cards -->
        <!-- <VCard class="mb-4">
            <VCardText>
                <SalarySummaryCards
                    :summary="summary"
                    :total-filtered="totalSalaries"
                />
            </VCardText>
        </VCard> -->

         <!-- Action Buttons -->
         <div class="table-action action mb-4 d-flex justify-end gap-4">
            <VBtn 
                prepend-icon="tabler-refresh" 
                variant="outlined" 
                @click="handleResetFilters"
            >
                Reset Filters
            </VBtn>

            <ExportTableSalaryReport 
                :data="salaries" 
                :headers="exportHeaders" 
                filename="salary-report"
                title="Salary Report"
                :summary-data="totalSalaries"
            />
        </div>


        <!-- Salary Report Table -->
        <SalaryReportTable
            :salaries="salaries"
            :export-headers="exportHeaders"
            :date-from="dateFrom"
            :date-to="dateTo"
            :selected-branch-name="selectedBranchName"
            :selected-employee-name="selectedEmployeeName"
            :is-loading="isLoading"
        />
    </div>
</template>

<style lang="scss" scoped>
.text-link {
    color: rgb(var(--v-theme-primary));
    text-decoration: none;

    &:hover {
        color: rgba(var(--v-theme-primary), 0.8);
    }
}

</style>
