<script setup>
import { computed, ref } from 'vue'
import { useSalaryReport } from '@/composables/useSalaryReport'
import SalaryReportFilters from '@/components/report/SalaryReportFilters.vue'
import SalaryReportTable from '@/components/report/SalaryReportTable.vue'
import ExportTableSalaryReport from '@/components/ExportTableSalaryReport.vue'

// Use the salary report composable
const {
    // State
    salaryData,
    isLoading,
    branchId,
    employeeId,
    dateFrom,
    dateTo,
    branches,
    employees,
    
    // Methods
    resetFilters,
    
    // Computed
    salaries,
    totalSalaries
} = useSalaryReport()



// Ref to store report header data from table component
const reportHeaderData = ref({
    reportTitle: 'Salary Report',
    outletName: 'All Outlets',
    phone: null,
    address: null,
    dateRange: 'N/A',
    generatedOn: '',
    generatedBy: 'N/A'
})

// Handle header data updates from table component
const handleHeaderDataUpdate = (headerData) => {
    reportHeaderData.value = headerData
}

// Computed properties
const selectedBranch = computed(() => {
    if (!branchId.value) return null
    return branches.value.find(b => b.id == branchId.value) || null
})

const selectedBranchName = computed(() => {
    if (!branchId.value) return 'All Outlets'
    return selectedBranch.value?.name || 'All Outlets'
})

const selectedEmployeeName = computed(() => {
    if (!employeeId.value) return 'All Employees'
    const employee = employees.value.find(e => e.id == employeeId.value)
    return employee?.name || 'All Employees'
})

const exportHeaders = computed(() => [
    { title: 'Generated Date', key: 'generated_date', sortable: true },
    { title: 'Month-Year', key: 'month', sortable: true },
    { title: 'Branch', key: 'branch.branch_name', sortable: false },
    { title: 'Total Amount', key: 'total_amount', sortable: true },
    { title: 'Payment Account', key: 'payment_method_name', sortable: false },
    { title: 'Generated By', key: 'user.name', sortable: false },
])

const handleResetFilters = () => {
    resetFilters()
}

const isFilterOptionsOpen = ref(false)

const toggleFilterOptions = () => {
  isFilterOptionsOpen.value = !isFilterOptionsOpen.value
}

</script>

<template>
    <div>
        

         <!-- Action Buttons -->
         <div class="table-action action mb-4 d-flex justify-end gap-4">
            <VBtn 
                :prepend-icon="isFilterOptionsOpen ? 'tabler-filter-off' : 'tabler-filter'" 
                variant="outlined"
                @click="toggleFilterOptions"
            >
                {{ isFilterOptionsOpen ? 'Hide Filters' : 'Filters' }}
            </VBtn>

            <VBtn 
                prepend-icon="tabler-refresh" 
                variant="outlined" 
                color="error"
                @click="handleResetFilters"
            >
                Reset Filters
            </VBtn>

            <ExportTableSalaryReport 
                :data="salaries" 
                :headers="exportHeaders" 
                filename="salary-report"
                title="Salary Report"
                :header-data="reportHeaderData"
                :summary-data="totalSalaries"
            />
        </div>

        <!-- Filter Section -->
        <VCard class="mb-4" v-if="isFilterOptionsOpen">
            <VCardText>
                <SalaryReportFilters
                    v-model:date-from="dateFrom"
                    v-model:date-to="dateTo"
                    v-model:branch-id="branchId"
                    v-model:employee-id="employeeId"
                    :branches="branches"
                    :employees="employees"
                />
            </VCardText>
        </VCard>


        <!-- Salary Report Table -->
        <SalaryReportTable
            :salaries="salaries"
            :export-headers="exportHeaders"
            :date-from="dateFrom"
            :date-to="dateTo"
            :selected-branch="selectedBranch"
            :selected-branch-name="selectedBranchName"
            :selected-employee-name="selectedEmployeeName"
            :is-loading="isLoading"
            @update:header-data="handleHeaderDataUpdate"
        />
    </div>
</template>

<style lang="scss" scoped>
.text-link {
    color: rgb(var(--v-theme-primary));
    text-decoration: none;

    &:hover {
        color: rgba(var(--v-theme-primary), 0.8);
    }
}

</style>
